상세페이지_하단네비게이션
teamesa/km-front pull request #93
Opened 2022-08-26 14:00 UTC by kimhan0421

## **📄 PR 카테고리**

- ⬜️ 리팩토링
- ⬜️ 화면 개발 ( 추가, 수정, 삭제 )
- ✅ QA 및 버그 수정
- ⬜️ 기타 ( 버전 업데이트 등 )

## **⌨️ 변경점**

1. 상세페이지 간격 수정
![image](https://user-images.githubusercontent.com/48988891/186918916-f9a66be6-6bec-48ae-8aaa-a81f28781276.png)

2. 하단 네비게이션 하트 픽 
-하트픽 안함
![image](https://user-images.githubusercontent.com/48988891/186919142-a276a13a-ff9d-4215-a789-f0ee477c7b7c.png)

- 하트픽 후
![image](https://user-images.githubusercontent.com/48988891/186919215-02eefd73-d14e-42ea-a003-687aa003344c.png)

3. 하단 네비게이션 공유링크

## **🤦🏻 고민한 부분**

## **🙋🏼‍♀️ 추가 논의가 필요한 부분**

## **✋ 추가 코멘트**

2022-08-26 18:38 UTC, mndangee commented on components/Organisms/Detail/NavigatorHeart.tsx
> +      <PopupRouter />
한솔님! 제가 <PopupRouter>를 _app.tsx에다 공통(?)으로 선언해서 따로 선언 안해주셔도 될 것 같은데
혹시 <PopupRouter>가 없으면 팝업이 안뜨시나용?!

2022-08-27 01:16 UTC, azxca1731 requested changes

2022-08-27 01:16 UTC, azxca1731 commented on components/Organisms/Detail/Description.tsx
> +    if (!link) {
위에서 정의 된 것에 따르면 link는 non-null인데 왜 밑에서 또 !link를 하신것일까요? 이유가 있을까요?

2022-08-27 01:16 UTC, azxca1731 commented on components/Organisms/Detail/Description.tsx
> +  const linkUrl = ({ title, link }: { title: string; link: string }) => {
함수명인지 정확히 모르겠어요. getLinkUrl or makeLinkUrl or generateLinkUrl 등이 더 바람직 해보입니다~

2022-08-27 01:16 UTC, azxca1731 commented on components/Organisms/Detail/Navigator.tsx
> +import useCopy from 'use-copy';
이 라이브러리는 뭔가요? 앞으로 추가 라이브러리 있을 때, 먼저 말씀해주세요!

2022-08-27 01:16 UTC, azxca1731 commented on components/Organisms/Detail/NavigatorHeart.tsx
> +        console.log(error);
여기서 error가 났을 때 console.log 보다 이제는 팝업이 생겼으니, 팝업으로 부탁드립니다~

2022-08-27 01:16 UTC, azxca1731 commented on package.json
> +    "react-copy-to-clipboard": "^5.0.4",
이건 왜 추가하신걸까요?

2022-08-27 01:49 UTC, truthone approved these changes

2022-09-07 04:51 UTC, closed without merging